{% set name = "automap" %}
{% set version = "0.6.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f9b93308ca3b4fc69d7fa757fbfa01b4e952a298fc7a6cc8b6adfb1fa966bfcc

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - {{ name }}

about:
  home: https://github.com/brandtbucher/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: High-performance autoincremented integer-valued mappings.
  dev_url: https://github.com/brandtbucher/{{ name }}

extra:
  recipe-maintainers:
    - brandtbucher
